### ISSUE TITLE
Not work with php 8

### ISSUE THREAD

**Issue by quyle92** [ash-jc-allen/laravel-executor#19]
Hi there,
Before asking question, I'd like to thank you for making very useful plugin for Laravel community.
I've just installed your package but it does not seems to work with my current php8.2 and laravel 10.
Here is the full errors from my composer:
```
 Problem 1
    - ashallendesign/laravel-executor[v0.1.0, ..., v0.3.0, v1.0.0, ..., v1.1.0, v2.0.0, ..., v2.1.1] 
    require php ^7.2 -> your php version (8.2.6) does not satisfy that requirement.
    
    - ashallendesign/laravel-executor v2.2.0 requires illuminate/container ^6.0|^7.0|^8.0 
    -> found illuminate/container[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27]
     but these were not loaded, likely because it conflicts with another require.
     
    - Root composer.json requires ashallendesign/laravel-executor * 
    -> satisfiable by ashallendesign/laravel-executor[v0.1.0, ..., v0.3.0, v1.0.0, v1.0.1, v1.1.0,
     v2.0.0, v2.1.0, v2.1.1, v2.2.0].
```

Can you please help?

Thank you,
Quy

**Comment by ash-jc-allen** [comment]
Hey @quyle92! Thanks for the kind words 😄

Unfortunately, I've not been keeping this package up to date because it never gained any traction. So I don't really have any plans to update this to work with the latest versions of PHP or Laravel, sorry.

I hope you manage to find an alternative solution though for your project! 😄
